# Generated by Django 6.0 on 2026-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_zarek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('afbeeld1', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('afbeeld2', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
