# Generated by Django 6.0 on 2026-01-20 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_zarek', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
