# Generated by Django 6.0 on 2026-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_zarek', '0003_portfolio_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='afbeeld3',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='afbeeld4',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='afbeeld5',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='afbeeld6',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
